language: go
go:
- 1.8.x

install:
- go get gopkg.in/alecthomas/kingpin.v2
- go get gopkg.in/jarcoal/httpmock.v1
- go install

script: go test ./ -cover -coverprofile=coverage.out -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
